#!/bin/bash
# /etc/libvirt/hooks/qemu
OBJECT="$1"
OPERATION="$2"

case "$OPERATION" in
"prepare")
    systemctl start libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    /home/qiu/.qemu/start.sh 2>&1 | tee -a /var/log/qemustart.log
    ;;

"release")
    systemctl stop libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    /home/qiu/.qemu/stop.sh 2>&1 | tee -a /var/log/qemustop.log
    ;;
esac
